# BloodSampling Example

This is an example of how to use the `BloodSampling` class to parse and use the data form the BloodSampling excel files.

- Import the data parsers

In [1]:
import src.data as d

- Load the data from the input files and parse it into a more convenient format. (using the BloodSamplingData class)

In [2]:
file_path = "./sample_files/Blood sampling - data 22 weeks.xls"
bloodData = d.BloodSamplingData(file_path)

Successfully loaded blood sampling data
rows: 92
columns: 20

In [ ]:
# to acces the data frame use the df attribute
bloodData.df.shape
bloodData.df.sample(10)

,sequence_number,first_animal_V,unknown_animal_V,Brokkalf_V,scan_work_number,injection,ear_tag_country,ear_tag_number,hb_1,hb_2,hb_3,hb_4,hb_5,serum_2,serum_3,serum_4,serum_5,department_number,coat_color,sex
59,56,NaN,NaN,NaN,05045,NaN,DK,03711505045,4.9,5.5,5.2,5.3,NaN,39.1,20,28.2,NaN,2,Zwartbont,M
81,76,NaN,NaN,NaN,6509,NaN,FR,6214786509,4.1,4.5,6.3,6.6,NaN,33.1,52.4,39.9,NaN,3,Zwartbont,M
13,12,NaN,NaN,NaN,73623,NaN,DE,0365073623,5.7,7.5,5.2,5.5,NaN,35.3,32.3,27.1,NaN,1,Zwartbont,M
61,58,NaN,NaN,NaN,71355,NaN,DE,0542571355,5.7,5.9,6,6.8,NaN,36.9,53.7,47.4,NaN,3,Zwartbont,M
55,52,NaN,NaN,NaN,06911,NaN,DK,03245206911,6.7,6.5,5.3,4.7,NaN,30.9,25.2,20.9,NaN,2,Zwartbont,M
87,82,NaN,NaN,NaN,0032,NaN,BE,628660032,5.6,5.8,5.5,6.6,NaN,39.4,27.7,27.1,NaN,4,Zwartbont,M
76,73,NaN,NaN,NaN,0370,NaN,FR,6208490370,6.3,4.5,4.7,5,NaN,21.8,18.5,22.3,NaN,3,Zwartbont,M
77,74,NaN,NaN,NaN,9820,NaN,FR,4477709820,6.8,5,4.9,5.4,NaN,30.8,30.4,47.5,NaN,3,Zwartbont,M
60,57,#,NaN,NaN,74882,NaN,DE,1306874882,5.9,5.7,5.8,6,NaN,38.5,66.5,70.3,NaN,3,Zwartbont,M
95,90,NaN,NaN,NaN,8782,NaN,NL,713087824,7.3,5.4,6.3,5.8,NaN,NaN,25.8,27.3,NaN,4,Roodbont,M

In [4]:
# I also managed to load in the metadata from the excel file, and it has some useful information
print('company:\n', bloodData.meta.company_name)
print('\nmeasurement date:\n', bloodData.meta.measurement_date)
print('\nweek number:\n', bloodData.meta.week_number)

company:
 Kalvermesterij Hooijer B.V.

measurement date:
 2023-12-05 00:00:00

week number:
 22