# BloodSampling Example

This is an example of how to use the `BloodSampling` class to parse and use the data form the BloodSampling excel files.

- Import the data parsers

In [1]:
import aifarming.data as d

- Load the data from the input files and parse it into a more convenient format. (using the BloodSamplingData class)

In [4]:
file_path = "../sample_files/blood_sampling/2229248 Borne v.d.  blood samples.xlsx"
bloodData = d.BloodSamplingData(file_path)

In [5]:
# to acces the data frame use the df attribute
bloodData.df.shape
bloodData.df.sample(10)

,sequence_number,first_animal_V,unknown_animal_V,Brokkalf_V,scan_work_number,injection,ear_tag_country,ear_tag_number,HbWaarde1_V,HbWaarde2_V,...,HbWaarde4_V,HbWaarde5_V,serum_2,serum_3,serum_4,serum_5,department_number,coat_color,sex,id
18,17,NaN,NaN,NaN,69034,NaN,DE,1406869034,5.3,7.1,...,7.1,NaN,NaN,NaN,179,NaN,1,Zwartbont,M,DE1406869034
9,8,#,NaN,NaN,23107,NaN,DE,1505423107,5.4,5.1,...,4.2,NaN,NaN,19.5,20.9,NaN,1,Zwartbont,M,DE1505423107
69,66,NaN,NaN,NaN,0185,NaN,FR,5641400185,4.3,4.5,...,5.7,NaN,NaN,NaN,23.5,NaN,3,Zwartbont,M,FR5641400185
8,7,NaN,NaN,NaN,62833,NaN,DE,1406762833,6.1,5.9,...,6.2,NaN,35.2,36.8,38.9,NaN,1,Zwartbont,M,DE1406762833
13,12,NaN,NaN,NaN,73623,NaN,DE,0365073623,5.7,7.5,...,5.5,NaN,35.3,32.3,27.1,NaN,1,Zwartbont,M,DE0365073623
6,5,NaN,NaN,NaN,42840,NaN,DE,1406642840,5.8,5.6,...,5.8,NaN,53.9,52.2,47.1,NaN,1,Zwartbont,M,DE1406642840
14,13,NaN,NaN,NaN,38290,NaN,DE,0365038290,7.4,6.3,...,6.4,NaN,35.9,47.3,47.1,NaN,1,Zwartbont,M,DE0365038290
86,81,NaN,NaN,NaN,2307,NaN,BE,037172307,6.3,6.4,...,6.9,NaN,NaN,NaN,22.1,NaN,4,Zwartbont,V,BE037172307
70,67,NaN,NaN,NaN,6537,NaN,FR,4905896537,6,4.1,...,5,NaN,NaN,NaN,20.9,NaN,3,Zwartbont,M,FR4905896537
97,91,NaN,NaN,NaN,NaN,NaN,nan,nan,5.913187,5.652747,...,5.876923,NaN,32.456364,36.951316,34.96044,NaN,NaN,NaN,NaN,nannan

In [4]:
# I also managed to load in the metadata from the excel file, and it has some useful information
print('company:\n', bloodData.meta.company_name)
print('\nmeasurement date:\n', bloodData.meta.measurement_date)
print('\nweek number:\n', bloodData.meta.week_number)

company:
 Kalvermesterij Hooijer B.V.

measurement date:
 2023-12-05 00:00:00

week number:
 22