# BloodSampling Example

This is an example of how to use the `BloodSampling` class to parse and use the data form the BloodSampling excel files.

- Import the data parsers

In [1]:
import aifarming.data as d

- Load the data from the input files and parse it into a more convenient format. (using the BloodSamplingData class)

In [2]:
file_path = "../sample_files/blood_sampling/only_one/Blood sampling - data 22 weeks.xls"
bloodData = d.BloodSamplingData(file_path)

In [6]:
# to acces the data frame use the df attribute
bloodData.df.shape
bloodData.df.sample(10)

,sequence_number,first_animal_V,unknown_animal_V,Brokkalf_V,scan_work_number,injection,ear_tag_country,ear_tag_number,HbWaarde1_V,HbWaarde2_V,...,HbWaarde4_V,HbWaarde5_V,serum_2,serum_3,serum_4,serum_5,department_number,coat_color,sex,id
10,9,NaN,NaN,NaN,24055,NaN,DE,0364624055,5.2,7.7,...,6,NaN,NaN,51.1,34.5,NaN,1,Zwartbont,M,DE0364624055
81,76,NaN,NaN,NaN,6509,NaN,FR,6214786509,4.1,4.5,...,6.6,NaN,33.1,52.4,39.9,NaN,3,Zwartbont,M,FR6214786509
47,44,NaN,NaN,NaN,07082,NaN,DK,03998007082,6.2,5.7,...,5.9,NaN,33.2,52.4,37.4,NaN,2,Wit-blauw stier,M,DK03998007082
83,78,NaN,NaN,NaN,4728,NaN,FR,3512844728,5.7,5.3,...,6.1,NaN,NaN,NaN,27,NaN,3,Zwartbont,M,FR3512844728
91,86,NaN,NaN,NaN,7259,NaN,NL,574672599,5.3,5.8,...,5.5,NaN,NaN,34.1,27.2,NaN,4,Roodbont,M,NL574672599
39,36,NaN,NaN,NaN,04995,NaN,DK,04534004995,5.7,4.9,...,5.3,NaN,26.3,25.2,25.9,NaN,2,Zwartbont,M,DK04534004995
62,59,NaN,NaN,NaN,0401,NaN,NL,591904015,5.7,5.7,...,5.2,NaN,21.6,26.5,29.6,NaN,3,Zwartbont,M,NL591904015
85,80,NaN,NaN,NaN,4330,NaN,BE,917694330,6.1,6.4,...,5.8,NaN,NaN,NaN,27.3,NaN,4,Zwartbont,V,BE917694330
74,71,NaN,NaN,NaN,1106,NaN,FR,3528171106,7.8,5,...,6.5,NaN,NaN,38.2,31,NaN,3,Zwartbont,M,FR3528171106
46,43,#,NaN,NaN,12196,NaN,DK,04129512196,6.3,7.1,...,6.4,NaN,NaN,35.5,36.2,NaN,2,Wit-blauw stier,V,DK04129512196

In [5]:
# I also managed to load in the metadata from the excel file, and it has some useful information
print('company:\n', bloodData.meta.company_name)
print('\nmeasurement date:\n', bloodData.meta.measurement_date)
print('\nweek number:\n', bloodData.meta.week_number)

company:
 Kalvermesterij Hooijer B.V.

measurement date:
 2023-12-05 00:00:00

week number:
 22